### PR TITLE
Talib example

### PR DESCRIPTION
**Pull request by damo1884**
Simple TALib Example with SMA, RSI, STOCH, MACD & Charting

### CODE REVIEW

**Comment by damo1884** [comment]
Fixed Candlestick charting issue and added porfolio value plot
image

image

**Comment by abnera** [comment]
Any updates on this PR?

**Comment by fredfortier** [comment]
Thanks for the reminder! I'm going to test it and merge now.

**Comment by fredfortier** [comment]
Beautiful! Merging.
screenshot 2017-11-16 16 52 08

**Pull request merged**
