### PR TITLE
Fix 'H' timeframe support

### PR DESCRIPTION
**Pull request by vonpupp**
Fix to support "H" timeframes.

The issue is explained in #114.

### CODE REVIEW

**Comment by fredfortier** [comment]
Thanks! We're organizing this in a separate branch which is why we did not include in this version but this is super helpful.

**Comment by fredfortier** [comment]
@lenak25 this looks good to me so I will be merging into develop and test. Please take a look as well on Sunday.

**Comment by lenak25** [comment]
Thanks @vonpupp for your PR!
This indeed seems to fix the live case. 
We will need to apply some adjustments to address this issue in backtest as well.
Thanks again!

**Comment by vonpupp** [comment]
Thank you @lenak25.

Yes, I am aware of such things, however I handle them internally on an intermediate layer I made for my algos on top of Catalyst. Unfortunately this layer doesn't fit within Catalyst itself, otherwise I would PR it also.

**Pull request merged**
