### PR TITLE
Stop trying to handle signals when inside thread

### PR DESCRIPTION
**Pull request by caioaao**
Plus exposed the code for exiting the algorithm.

IMO this is a really bad design. It's a violation of separation of concerns and there's no reason to keep this signal handling on this class, but the code is not well tested and I'm afraid to mess this up even further by refactoring it...

### CODE REVIEW

**Comment by fredfortier** [comment]
Agreed. This was done pragmatically to run ‘analyze’ on exit but I
understand the issue based on what you are trying to do. Will modify ASAP.

**Comment by caioaao** [comment]
@fredfortier I think this PR is probably enough for fixing it, but IMO the algorithm should be controllable from outside (IE: always running the algorithm in a separate thread and expose some API to start/stop/wait). without this, using this in prod is not ideal, as I have to work around the API to do stuff like a panic button (cancel orders, sell everything and stop trading). I'll try experimenting with this concept this week on my fork and will open a PR or an issue to discuss it when I have a clearer idea about how it would work, but basically what I have in mind is something like this:
```python
with build_algorithm(...) as algo:
    def user_input_handler(event):
        if event == "bail":
            algo.sell_all()
        elif event == "panic":
            algo.sell_all()
            algo.stop()        
```
(in this case `algo.close()` would block until the algorithm exits)

**Comment by fredfortier** [comment]
Agreed. We've been focused on the Zipline interfaces (`run_algorithm()`,
CLI and Jupyter Notebook) but I agree that a controller capable of managing
each algo as a thread would be more powerful. We'll have more availability
this week after the holidays to work with you to make this happen.

**Comment by caioaao** [comment]
Great! It's my last week on vacation, so I'll probably be focused on making my current algo run. I also imagine this shouldn't be a priority for you guys right now, as the code is still filled with bugs and the catalyst platform should be a big project as well, so don't worry if you can't prioritize this right now.
I also think it'd be more beneficial to think about a deeper re-design than on specific use cases. zipline was a good starting point, but there are intrinsic differences to their goal. zipline is basically a backtesting engine, with the IB being the "prod" interface and probably responsible for the robustness of the system as a whole. if catalyst is to be a complete project for backtesting, being used in the enigma platform and a standalone live trading library, there should be some serious changes. also, as the code today is buggy and hard to test (both symptoms of a poorly designed system IMO), a more careful rewrite around the core classes (basically the blotter, exchange, clock) could be easier than trying to fix the current implementation. ofc my opinion is based on a shallow read through the code and a 1-week experience with it, so take it with a grain of salt :)

**Comment by fredfortier** [comment]
We’re currently focusing our energy improving unit tests in order to have a
have coverage and take care any bugs. I believe that we’re much closer than
you’re suggesting but there’s certainly work to be done. We’re planning to
achieve full coverage by the end of this week. This include random sampling
of exchanges and assets for each operation to account for differences in
behavior between exchanges. We’re also still refactoring things following
CCXT integration which will allow us to streamline some components
especially around the asset finder and data portal. That’s why some things
are in a transitory state in the ‘develop’ branch (the ‘skip_init’ issue
for example). We certainly appreciate your feedback and help. Using Zipline
does have benefits, but we’ll continue to refactor things incrementally as
we move closer to integration with the Enigma protocol.

**Comment by caioaao** [comment]
Ok, I'll wait then. I'll keep working on my fork and we can revisit this
discussion after the unit tests are done, if that's ok with you.

Em seg, 1 de jan de 2018 às 22:32, Frederic Fortier <
notifications@github.com> escreveu:

**Comment by fredfortier** [comment]
Sounds great, thanks for your patience. Looking forward to exchanging more
ideas with you!

**Pull request merged**
