### PR TITLE
Example: Simple Universe

### PR DESCRIPTION
**Pull request by abnera**
### Description:
This example aims to help users get familiar with catalyst API's to collect and handle data.

### Features:
1. How to create a universe
2. How to Filter a universe
3. Collect ohlcv data
4. Update function daily
5. Update function every 30 minutes

### Test
```
source activate catalyst
python simple_universe.py
```

Currently, it throws errors due to catalyst bugs but it should not throw errors in the future.

A similar version can be used for unit testing ALL currency pairs for all exchanges
Feel free to update/upgrade to your needs.

### CODE REVIEW

**Comment by abnera** [comment]
@lacabra 
This example is fully tested on v0.3.3 and ready to be merged.
Test instructions are provided, so please ensure it works on your computer before merging.

**Comment by abnera** [comment]
This PR I believe is ready to be merged. Feel free to suggest improvements before merging and I'll do my best to comply.

**Comment by fredfortier** [comment]
Merged into the develop branch.

**Comment by lacabra** [comment]
Thanks @abnera for this submission, this is great! 👍

**Pull request merged**
